/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Equipo_7;

import Equipo_7.DB.Database_Service;
import Equipo_7.Negocio.Logica_De_Negocio;
import Equipo_7.Negocio.Trabajador;
import Equipo_7.Negocio.ValidatorClass;
import javax.swing.JOptionPane;

/**
 *
 * @author SrMrPandora
 */
public class Form2 extends javax.swing.JFrame {

    private Database_Service SQLite = new Database_Service();
    Logica_De_Negocio validacion = new Logica_De_Negocio();

    /**
     * Creates new form main
     */
    public Form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RFC_txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Seguro = new javax.swing.JLabel();
        Seguro_Social_txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Nombre_jl = new javax.swing.JLabel();
        Nombre_txt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Email_jl = new javax.swing.JLabel();
        Email_txt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Sexo_Combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Fecha_Alta_txt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Departamento_Combo = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SueldoB_txt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        AltaIMSS_txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Btn_guardar = new javax.swing.JButton();
        Btn_Buscar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("RFC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        RFC_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RFC_txt.setBorder(null);
        RFC_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RFC_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RFC_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RFC_txtKeyTyped(evt);
            }
        });
        jPanel1.add(RFC_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 202, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 10));

        Seguro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Seguro.setText("Numero de seguro social");
        jPanel1.add(Seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        Seguro_Social_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Seguro_Social_txt.setBorder(null);
        Seguro_Social_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seguro_Social_txtActionPerformed(evt);
            }
        });
        Seguro_Social_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Seguro_Social_txtKeyPressed(evt);
            }
        });
        jPanel1.add(Seguro_Social_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 310, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 310, 10));

        Nombre_jl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nombre_jl.setText("Nombre Completo");
        jPanel1.add(Nombre_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Nombre_txt.setBackground(new java.awt.Color(255, 245, 241));
        Nombre_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nombre_txt.setBorder(null);
        jPanel1.add(Nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 580, 10));

        Email_jl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Email_jl.setText("E - Mail");
        jPanel1.add(Email_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        Email_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email_txt.setBorder(null);
        Email_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_txtFocusLost(evt);
            }
        });
        Email_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Email_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 290, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 290, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Fecha De Alta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        Sexo_Combo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sexo_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Hombre", "otro" }));
        Sexo_Combo.setAutoscrolls(true);
        Sexo_Combo.setBorder(null);
        jPanel1.add(Sexo_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Departameno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        Fecha_Alta_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fecha_Alta_txt.setBorder(null);
        Fecha_Alta_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Fecha_Alta_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fecha_Alta_txtKeyTyped(evt);
            }
        });
        jPanel1.add(Fecha_Alta_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 230, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 230, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("SEXO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        Departamento_Combo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Departamento_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seguridad Informática", "Soporte Técnico", "Auditoría de Gastos", "Gestión de Impuestos", "Proyección Bancaria", "Prospección de Clientes", "Cierre de Negocios", "Análisis de Mercado" }));
        Departamento_Combo.setAutoscrolls(true);
        Departamento_Combo.setBorder(null);
        jPanel1.add(Departamento_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 280, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 620, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Alta del IMSS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Sueldo Base");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        SueldoB_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SueldoB_txt.setBorder(null);
        SueldoB_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SueldoB_txtKeyTyped(evt);
            }
        });
        jPanel1.add(SueldoB_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 230, 10));

        AltaIMSS_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AltaIMSS_txt.setBorder(null);
        AltaIMSS_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AltaIMSS_txtKeyTyped(evt);
            }
        });
        jPanel1.add(AltaIMSS_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 200, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 200, 10));

        Btn_guardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_guardar.setText("Guardar");
        Btn_guardar.setBorder(null);
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 100, 40));

        Btn_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Buscar.setText("Buscar");
        Btn_Buscar.setBorder(null);
        Btn_Buscar.setBorderPainted(false);
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 90, 40));

        Btn_Limpiar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(null);
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RFC_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RFC_txtKeyPressed
        char c = evt.getKeyChar();
        int keyCode = evt.getKeyCode();
        String currentText = RFC_txt.getText();

        if (keyCode == java.awt.event.KeyEvent.VK_BACK_SPACE
                || keyCode == java.awt.event.KeyEvent.VK_DELETE
                || keyCode == java.awt.event.KeyEvent.VK_LEFT
                || keyCode == java.awt.event.KeyEvent.VK_RIGHT) {
            return;
        }

        if (currentText.length() >= 13) {
            evt.consume();
            return;
        }

        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
            c = Character.toUpperCase(c);
        }

        if (!String.valueOf(c).matches("[A-Z0-9Ñ&]")) {
            evt.consume();
        }
    }//GEN-LAST:event_RFC_txtKeyPressed

    private void RFC_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RFC_txtKeyReleased
        char c = evt.getKeyChar();
        String currentText = RFC_txt.getText();

        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
            c = Character.toUpperCase(c);
        }

        if (currentText.length() >= 13
                && evt.getKeyCode() != java.awt.event.KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume();
            return;
        }

        if (c != java.awt.event.KeyEvent.CHAR_UNDEFINED && Character.isDefined(c)) {
            if (!String.valueOf(c).matches("[A-Z0-9Ñ&]")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_RFC_txtKeyReleased

    private void RFC_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RFC_txtKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
            c = Character.toUpperCase(c);
        }

        if (RFC_txt.getText().length() >= 13) {
            evt.consume(); // Detiene la escritura
            return;
        }

        String permitidos = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ0123456789&";
        if (permitidos.indexOf(c) < 0 && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_RFC_txtKeyTyped

    private void Seguro_Social_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seguro_Social_txtKeyPressed
        int keyCode = evt.getKeyCode();
        char c = evt.getKeyChar();

        if (keyCode == java.awt.event.KeyEvent.VK_BACK_SPACE
                || keyCode == java.awt.event.KeyEvent.VK_DELETE
                || keyCode == java.awt.event.KeyEvent.VK_LEFT
                || keyCode == java.awt.event.KeyEvent.VK_RIGHT) {
            return;
        }

        if (Seguro_Social_txt.getText().length() >= 11) {
            evt.consume();
            return;
        }

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Seguro_Social_txtKeyPressed

    private void Fecha_Alta_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fecha_Alta_txtKeyReleased
        // TODO add your handling code here:
        String texto = Fecha_Alta_txt.getText();
        int largo = texto.length();

        if (evt.getKeyCode() != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            if (largo == 2 || largo == 5) {
                Fecha_Alta_txt.setText(texto + "/");
            }
        }
    }//GEN-LAST:event_Fecha_Alta_txtKeyReleased

    private void Fecha_Alta_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fecha_Alta_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || Fecha_Alta_txt.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_Fecha_Alta_txtKeyTyped

    private void Email_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Email_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String Texto = Email_txt.getText();
        if (Character.isUpperCase(c)) {
            evt.setKeyChar(Character.toLowerCase(c));
            c = Character.toLowerCase(c);
        }

        if (c == ' ') {
            evt.consume();
            return;
        }

        if (c == '@' && Texto.contains("@")) {
            evt.consume();
            return;
        }

        if (!String.valueOf(c).matches("[a-z0-9@._-]")) {
            evt.consume();
        }
    }//GEN-LAST:event_Email_txtKeyTyped

    private void Email_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_txtFocusLost
        // TODO add your handling code here:
        String email = Email_txt.getText();

        String patron = "^[a-z0-9._-]+@[a-z0-9.-]+\\.[a-z]{2,6}$";

        if (!email.matches(patron)) {
            Email_txt.setBackground(new java.awt.Color(255, 200, 200));
        } else {
            Email_txt.setBackground(java.awt.Color.WHITE);
        }
    }//GEN-LAST:event_Email_txtFocusLost

    private void SueldoB_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SueldoB_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String texto = SueldoB_txt.getText();

        if (!String.valueOf(c).matches("[0-9.]")) {
            evt.consume();
            return;
        }

        if (c == '.' && texto.contains(".")) {
            evt.consume();
        }

        if (c == '.' && texto.length() == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_SueldoB_txtKeyTyped

    private void AltaIMSS_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AltaIMSS_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String texto = AltaIMSS_txt.getText();

        if (!String.valueOf(c).matches("[0-9.]")) {
            evt.consume();
            return;
        }

        if (c == '.' && texto.contains(".")) {
            evt.consume();
        }

        if (c == '.' && texto.length() == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_AltaIMSS_txtKeyTyped

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        // TODO add your handling code here:
        RFC_txt.setText("");
        AltaIMSS_txt.setText("");
        Email_txt.setText("");
        Fecha_Alta_txt.setText("");
        Nombre_txt.setText("");
        Seguro_Social_txt.setText("");
        SueldoB_txt.setText("");
        Email_txt.setBackground(java.awt.Color.WHITE);

    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        // TODO add your handling code here:
    String idTexto = JOptionPane.showInputDialog("insertar el ID para buscar:");
    Logica_De_Negocio logica = new Logica_De_Negocio();
    Trabajador t = logica.BuscarTrabajador(idTexto);
    
    if (t != null) {
        // Llenar los campos con los datos encontrados
        Nombre_txt.setText(t.getNombre());
        Email_txt.setText(t.getEmail());
        RFC_txt.setText(t.getRFC());
        Fecha_Alta_txt.setText(t.getFechadeAlta());
        Seguro_Social_txt.setText(t.getSeguroSocial());
        Departamento_Combo.setSelectedItem(t.getDepartamento());
        SueldoB_txt.setText(String.valueOf(t.getSueldo()));
        AltaIMSS_txt.setText(t.getAltaImss());
    } else {
        JOptionPane.showMessageDialog(this, 
            "no se encontro ningun trabajador con el ID: " + idTexto,
            "no encontrado", 
            JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
        Trabajador Tabajo = new Trabajador( Nombre_txt.getText()
        ,
                Email_txt.getText()
        ,
                RFC_txt.getText()
        ,
                Seguro_Social_txt.getText()        
        ,              
                Fecha_Alta_txt.getText()
        ,
                Sexo_Combo.getSelectedItem().toString()
        ,
                Departamento_Combo.getSelectedItem().toString()
        ,
                SueldoB_txt.getText()
        ,
                AltaIMSS_txt.getText());
       
    String error = ValidatorClass.validarTrabajador(Tabajo);
        
    if (error != null) {
        JOptionPane.showMessageDialog(this, error, "error de validacion", JOptionPane.WARNING_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(this, "trabajador guardado correctamente.");
    }//GEN-LAST:event_Btn_guardarActionPerformed

    private void Seguro_Social_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seguro_Social_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seguro_Social_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

 

   

    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {

            new Form2().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AltaIMSS_txt;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JComboBox<String> Departamento_Combo;
    private javax.swing.JLabel Email_jl;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JTextField Fecha_Alta_txt;
    private javax.swing.JLabel Nombre_jl;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JTextField RFC_txt;
    private javax.swing.JLabel Seguro;
    private javax.swing.JTextField Seguro_Social_txt;
    private javax.swing.JComboBox<String> Sexo_Combo;
    private javax.swing.JTextField SueldoB_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
