/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Equipo_7;

import Equipo_7.DB.Database_Service;
import javax.swing.JOptionPane;

/**
 *
 * @author SrMrPandora
 */
public class Form1 extends javax.swing.JFrame {

    private Database_Service SQLite = new Database_Service();
    
    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RFC_txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Seguro = new javax.swing.JLabel();
        Seguro_Social_txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Nombre_jl = new javax.swing.JLabel();
        Nombre_txt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Email_jl = new javax.swing.JLabel();
        Email_txt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Sexo_Combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Fecha_Alta_txt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Departamento_Combo = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SueldoB_txt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        AltaIMSS_txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btn_Guardar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("RFC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        RFC_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RFC_txt.setBorder(null);
        jPanel1.add(RFC_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 202, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 10));

        Seguro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Seguro.setText("Numero de seguro social");
        jPanel1.add(Seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        Seguro_Social_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Seguro_Social_txt.setBorder(null);
        jPanel1.add(Seguro_Social_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 310, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 310, 10));

        Nombre_jl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nombre_jl.setText("Nombre Completo");
        jPanel1.add(Nombre_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Nombre_txt.setBackground(new java.awt.Color(255, 245, 241));
        Nombre_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nombre_txt.setBorder(null);
        jPanel1.add(Nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 580, 10));

        Email_jl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Email_jl.setText("E - Mail");
        jPanel1.add(Email_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        Email_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email_txt.setBorder(null);
        jPanel1.add(Email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 290, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 290, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Fecha De Alta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        Sexo_Combo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sexo_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Hombre", "otro" }));
        Sexo_Combo.setAutoscrolls(true);
        Sexo_Combo.setBorder(null);
        jPanel1.add(Sexo_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Departameno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        Fecha_Alta_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fecha_Alta_txt.setBorder(null);
        jPanel1.add(Fecha_Alta_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 230, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 230, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("SEXO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        Departamento_Combo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Departamento_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seguridad Informática", "Soporte Técnico", "Auditoría de Gastos", "Gestión de Impuestos", "Proyección Bancaria", "Prospección de Clientes", "Cierre de Negocios", "Análisis de Mercado" }));
        Departamento_Combo.setAutoscrolls(true);
        Departamento_Combo.setBorder(null);
        jPanel1.add(Departamento_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 280, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 620, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Alta del IMSS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Sueldo Base");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        SueldoB_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SueldoB_txt.setBorder(null);
        jPanel1.add(SueldoB_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 230, 10));

        AltaIMSS_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AltaIMSS_txt.setBorder(null);
        jPanel1.add(AltaIMSS_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 200, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 200, 10));

        btn_Guardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.setBorder(null);
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 100, 40));

        btn_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.setBorder(null);
        btn_Buscar.setBorderPainted(false);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 90, 40));

        btn_Limpiar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.setBorder(null);
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
       String emailBusqueda = JOptionPane.showInputDialog(
    this, 
    "introduzca el email para buscar:", 
    "busqueda de usuario", 
    JOptionPane.QUESTION_MESSAGE
);

if (emailBusqueda != null && !emailBusqueda.isEmpty()) {
    System.out.println("buscando a: " + emailBusqueda);
} else {
    System.out.println("busqueda cancelada o campo vacío.");
}
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        RFC_txt.setText("");
        AltaIMSS_txt.setText("");
        Email_txt.setText("");
        Fecha_Alta_txt.setText("");
        Nombre_txt.setText("");
        Seguro_Social_txt.setText("");
        SueldoB_txt.setText("");
        Email_txt.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        try{
            SQLite.insertarRegistro(Nombre_txt.getText(), 
                    Email_txt.getText(), 
                    RFC_txt.getText(), 
                    Fecha_Alta_txt.getText(),
                    Sexo_Combo.getSelectedItem().toString(),
                    Departamento_Combo.getSelectedItem().toString(),
                    Double.parseDouble(SueldoB_txt.getText()),
                    AltaIMSS_txt.getText());
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e, "error al registrar", ERROR);
        }
        
        

    }//GEN-LAST:event_btn_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AltaIMSS_txt;
    private javax.swing.JComboBox<String> Departamento_Combo;
    private javax.swing.JLabel Email_jl;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JTextField Fecha_Alta_txt;
    private javax.swing.JLabel Nombre_jl;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JTextField RFC_txt;
    private javax.swing.JLabel Seguro;
    private javax.swing.JTextField Seguro_Social_txt;
    private javax.swing.JComboBox<String> Sexo_Combo;
    private javax.swing.JTextField SueldoB_txt;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
